---
# drupaldev-vm travis testing file.
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:

  # Install Ansible.
  - pip install ansible

  # Install Ansible Lint
  - pip install ansible-lint

script:
  # Syntax check on all playbooks.
  - ansible-playbook -i localhost, provisioning/roles/common/tasks/main.yml --syntax-check

  # Lint Check on Ansible Playbooks
  # - ansible-lint -x resources provisioning/playbook.yml
